import { launch, openPage, dir } from "../harness.mjs";
const browser = await launch();
const errors = [];
const { p } = await openPage(browser, "dist/radar.html", { errors, label: "show", viewport: { width: 390, height: 780 } });
await p.goto("https://radar.test/", { waitUntil: "commit" });
await p.waitForFunction(() => window.__radarStarted === true, null, { timeout: 120000 });
await p.waitForFunction(() => !document.getElementById("loader"), null, { timeout: 60000 }).catch(() => {});
await p.waitForTimeout(2500);
const shot = async (n) => { await p.screenshot({ path: dir + `shots/v2-show-${n}.png` }); };
await p.evaluate(() => { document.getElementById("toasts").replaceChildren(); window.__radar.actions.setPlace("tromso"); window.__radar.setView("sky"); });
await p.waitForTimeout(1500);
const a = await p.evaluate(() => { const r = window.__radar; r.S.skyOffsetMin = 240; r.sky.view.yaw = 0; r.sky.view.pitch = 30; r.sky.view.fov = 85; return JSON.stringify({ aurora: r.sky.info.aurora, sunAlt: r.sky.info.sunAlt, limit: r.sky.info.limitMag }); });
console.log(a);
await p.waitForTimeout(1500);
await shot("tromso-north");
await p.evaluate(() => { document.getElementById("toasts").replaceChildren(); window.__radar.actions.setPlace("pune"); });
await p.waitForTimeout(800);
await p.evaluate(() => { const r = window.__radar; r.sky.opts.darkSky = true; r.sky.opts.constellations = true; r.sky.view.yaw = 250; r.sky.view.pitch = 35; r.sky.view.fov = 85; });
await p.waitForTimeout(1800);
await shot("pune-dark-lines");
await p.evaluate(() => { const r = window.__radar; r.sky.opts.darkSky = false; r.sky.opts.constellations = false; const pl = r.sky.planesNow.find((x) => x.el > 2); r.sky.view.yaw = pl.az; r.sky.view.pitch = Math.max(8, pl.el + 3); r.sky.view.fov = 45; });
await p.waitForTimeout(1500);
await shot("pune-plane");
console.log("errors:", errors.filter((e) => !/fonts\.g|ERR_FAILED/.test(e)));
await browser.close();
